travis:
  secure:
    BINSTAR_TOKEN: iHr/0Z9NYQoxew233My7wXjw10ffnFLPOX3kd6T34dcIbshUkrl2cyOOLD0OkER/WJaJll7QxT14dJxRpFHhpaykchM+pK+uOjeex1nUd73EYOVc7EHDd0l3JWQEawM3G9Fy2R4UQcHUdUmlwWbnylJ+BfQFg8amQKFkKvIAoTp6KO//YBga3y4mEnB0Xqms6R7fi5q3p8Nw2RMv5BGRTsIYirucPL1ux4+sD9GGGMKm63KSKALspoR1FjXRX3GvD427YjKeAls9JuYlzF0P8MIrjw/njAxLrvkySRAqh9WnAzTg8txo5LUAp3HcSGudueh7fuw6GwXsJpYcvnPYGk0TZEA6iK74mY/d0jMaLTIoinnLEMgVpFMZlA1gbtvi0MRsTscHjd7FPTMTSuK3KdeEGaOCgirRHjt8dPkYypAj2CfpZawInsyTKZ+YBZqFh2lTFUVIt9e+/IqtfjUrvfgiWEnwsQlRrd61iKBRDPXGNfQbUxgSUGXiyPYt7acwHxAAmOj5EmS6a3Pfs52zUZlg8IOjpgLXYo6dXOomivikF8gfIz/271YzpDJBVFT75uE9AX/ZKCDb1y1aV5f7F4rMyuxppZtOPVTExstd+8E4OV+B8zwLwvO2mzYM0xqGUeVyxRQpUm+HvTFLMyNjQfqXoYof6ffhcN4XaQQEihU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
