travis:
  secure:
    BINSTAR_TOKEN: BGDGJU/FiUGpvcuzZVHU8heTarxKjsK1iiKjFmgqXIYe05UqBzS2K5H+9M+Ezo5iudGOv3Ry7n1ewg73Z++IXiIALZNPQdyNJqBcZo7+0R1l1hJlfixK30LP1KceGtRTTytvsqxgvjnwwie0LjwNzkg1Wzgb/VI/eT1i7CR6UV34gwzyeSN15alzRMk98d9IxiRzs/Q/rpqjBc4G8Bzj2U3um6ivVN6QcmU5edAkv/izQcAmDt3/MP1TzY7Y81zOnFml+H8Ej0K/pS/Z+LsZytLEnmq49di0i0IBd5KywId5sICXKgL1AN4InhR4Sp55hq0yUcesYgNe0oZdifXA3zsV9/D+f53pz/HGxCyO83eJG1d+WObB0HlNoCy9Cskc7CrK4tX6VxoVvBM3YYwGpPvRCYM4Cfh21ycSzc2WkNRZwkP/+enxdL1XfShU6mnKcQ2LtJR6cIUsalknMfs8n747NHfdF7B8wgSePwQ4CQKLf0LzB2rbqkSqC9PY+4AgRgC0jQ7H+49ZrMg/gxAKICFrCu4cfoo4zngNAPgjc1wxmCtaWYv8WZWYeJUqTcLeAopeJz2wm0BCWiQOBEIh/ptmQz++wKuLrUzXWezhc8gqdKEFTbjmw5mWkMzj6RUcC6MdK7gw2RkZaCO0EOVj2F/il/I90eL0b59JMbaHlzQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
